name: Build, Package and Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install deps
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Build .deb
      run: chmod +x scripts/build-deb.sh && ./scripts/build-deb.sh

    - name: Import GPG key
      run: |
        echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 -d > private.key
        gpg --batch --import private.key
        rm private.key

    - name: Update APT repo
      run: |
        VERSION="1.0.0"
        mkdir -p repo/pool/main/t/themenal
        mv themenal_${VERSION}_amd64.deb repo/pool/main/t/themenal/

        cd repo

        dpkg-scanpackages pool /dev/null > dists/stable/main/binary-amd64/Packages
        gzip -kf dists/stable/main/binary-amd64/Packages

        apt-ftparchive release dists/stable > dists/stable/Release

        gpg --default-key ${{ secrets.GPG_KEY_ID }} \
            --batch --yes \
            --pinentry-mode loopback \
            --passphrase "${{ secrets.GPG_PASSPHRASE }}" \
            -abs -o dists/stable/Release.gpg dists/stable/Release

        gpg --default-key ${{ secrets.GPG_KEY_ID }} \
            --batch --yes \
            --pinentry-mode loopback \
            --passphrase "${{ secrets.GPG_PASSPHRASE }}" \
            --clearsign -o dists/stable/InRelease dists/stable/Release

        cd ..

    - name: Commit and push repo
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add repo
        git commit -m "Auto update APT repository"
        git push
